#!/usr/bin/env node

var util = require("./rotonde-utils.js");
var program = require("commander");
var fs = require("fs");
var crypto = require("crypto");

program
    .option("-u, --url [url]", "link to add to post")
    .option("-f, --focus [focus]", "percentage time spent on task")
    .option("-m, --media [media]", "media to link to in post (jpg, mp3)")
    .parse(process.argv);

var text = program.args[0];
if (!text) {
    console.error("error: specify an entry to post to your feed");
    return;
}

util.data().then((rotondeItems) => {
    var [rotonde, settings] = rotondeItems;
    var hash = crypto.createHash("sha256").update(text).digest("hex");
    var entry = {"text": text, "time": parseInt((new Date).getTime() / 1000), "id": hash}

    if (program.url) { entry["url"] = program.url; }
    if (program.media) { entry["media"] = program.media; }
    if (program.focus) { entry["focus"] = program.focus; }

    rotonde["feed"].push(entry);
    fs.writeFile(settings["rotonde location"], JSON.stringify(rotonde), function(err) {
        if (err) { 
            console.error("err: couldn't save to", settings["rotonde location"]);
            console.error(err);
            return;
        }
        console.log("the entry was published", text);
    })
})

