#!/usr/bin/env node

var rotonde = require("./rotonde-lib.js");
var util = require("./rotonde-utils.js");
var program = require("commander");

program.parse(process.argv);

var color = program.args[0];
if (!color) {
    console.error("error: the color to write on your profile");
    return;
}

rotonde.attribute("color", color)
