#!/usr/bin/env node

var rotonde = require("./rotonde-lib.js")
var util = require("./rotonde-utils.js")
var program = require("commander")

program.parse(process.argv)

var location = program.args[0]
if (!location) {
    console.error("error: the location to write on your profile")
    return
}

rotonde.attribute("location", location)
