#!/usr/bin/env node

var util = require("./rotonde-utils.js");
var rotonde = require("./rotonde-lib")
var program = require("commander");

program
    .option("-u, --url [url]", "link to add to post")
    .option("-f, --focus [focus]", "percentage time spent on task")
    .option("-m, --media [media]", "media to link to in post (jpg, mp3)")
    .parse(process.argv);

var text = program.args[0];
if (!text) {
    console.error("error: specify an entry to post to your feed");
    return;
}

rotonde.write(text, program.url, program.media, program.focus);
