#!/usr/bin/env node

var util = require("./rotonde-utils.js")
var rotonde = require("./rotonde-lib.js")
var program = require("commander")

program.parse(process.argv)

var portal = program.args[0]
if (!portal) {
    console.error("error: specify a portal to follow")
    return
}

rotonde.follow(portal)
