#!/usr/bin/env node

var rotonde = require("./rotonde-lib.js")
var util = require("./rotonde-utils.js")
var program = require("commander")

program.parse(process.argv)

var name = program.args[0]
if (!name) {
    console.error("error: the name to write on your profile")
    return
}

rotonde.attribute("name", name)
