#!/usr/bin/env node

var util = require("./rotonde-utils.js")
var program = require("commander")
var fs = require("fs")
var crypto = require("crypto")

program.parse(process.argv)

var index = program.args
if (!index.length) {
    console.error("error: specify an entry to post to your feed")
    return
}

util.data().then((rotondeItems) => {
    var [rotonde, settings] = rotondeItems
    index.forEach((i) => {
        if (i === "last") {
            rotonde["feed"].pop()
        } else {
            rotonde["feed"].splice(i, 1)
        }
    })
    fs.writeFile(settings["rotonde location"], JSON.stringify(rotonde), function(err) {
        if (err) { 
            console.error("err: couldn't save to", settings["rotonde location"])
            console.error(err)
            return
        }
        console.log("following entries were deleted:", index)
    })
})

