#!/usr/bin/env node

var util = require("./rotonde-utils.js");
var program = require("commander");
var fs = require("fs");
var crypto = require("crypto");

program.parse(process.argv);

var text = program.args[0];
if (!text) {
    console.error("error: specify an entry to post to your feed");
    return;
}

util.data().then((rotondeItems) => {
    var [rotonde, settings] = rotondeItems;
    var hash = crypto.createHash("sha256").update(text).digest("hex");
    rotonde["feed"].push({"text": text, "time": (new Date).getTime(), "id": hash});
    fs.writeFile(settings["rotonde location"], JSON.stringify(rotonde), function(err) {
        if (err) { 
            console.error("err: couldn't save to", settings["rotonde location"]);
            console.error(err);
            return;
        }
        console.log("the entry was published", text);
    })
})

