#!/usr/bin/env node

var rotonde = require("./rotonde-lib.js")
var util = require("./rotonde-utils.js")
var program = require("commander")

program.parse(process.argv)

var portal = program.args[0]
if (!portal) {
    console.error("error: specify a portal to unfollow")
    return
}

rotonde.unfollow(portal)


