#!/usr/bin/env node

var rotonde = require("./rotonde-lib.js")
var program = require("commander")
var path = require("path")

program.parse(process.argv)

var location = program.args[0]
if (!location) {
    console.log("please specify path to your rotonde.json file")
    return
}

if (path.parse(location).ext) {
    var rotondeFile = path.resolve(location)
} else {
    location = path.resolve(location)
    var rotondeFile = path.resolve(location, "rotonde.json")
}

console.log("saving the location of your rotonde file as", location + "...")
rotonde.save(rotondeFile)
